FROM node:22-slim

WORKDIR /app

# Copiar arquivos necessários para instalar deps
COPY package*.json ./
COPY prisma ./prisma/

# Instalar deps de DEV
RUN npm install --legacy-peer-deps

# Copiar código
COPY . .

# Gerar Prisma Client
RUN npx prisma generate

EXPOSE 3000 9229

CMD ["npm", "run", "start:dev"]
