export enum AppointmentType {
  CONSULTATION = 'CONSULTATION',
  FOLLOW_UP = 'FOLLOW_UP',
  ROUTINE_CHECKUP = 'ROUTINE_CHECKUP',
  EMERGENCY = 'EMERGENCY',
  SURGERY = 'SURGERY',
  EXAMINATION = 'EXAMINATION',
  VACCINATION = 'VACCINATION',
  OTHER = 'OTHER',
}
