export enum RecordType {
  CONSULTATION = 'CONSULTATION',
  EXAMINATION = 'EXAMINATION',
  SURGERY = 'SURGERY',
  EMERGENCY = 'EMERGENCY',
  ROUTINE_CHECKUP = 'ROUTINE_CHECKUP',
  FOLLOW_UP = 'FOLLOW_UP',
  DIAGNOSTIC = 'DIAGNOSTIC',
  OTHER = 'OTHER',
}
