export enum WardType {
  GENERAL = 'GENERAL',
  ICU = 'ICU',
  PEDIATRIC = 'PEDIATRIC',
  MATERNITY = 'MATERNITY',
  SURGERY = 'SURGERY',
  EMERGENCY = 'EMERGENCY',
  CARDIOLOGY = 'CARDIOLOGY',
  ONCOLOGY = 'ONCOLOGY',
  OTHER = 'OTHER',
}
